using System.Globalization;
using System.Text;
using Babelstone.Engine;
using Babelstone.FinancialTypes;

namespace Babelstone.Families.TermDeposit.Application.Tests;

/// <summary>
/// One captured event in a sealed expected-events sequence (ADR-PC-007 §P5): the durable
/// <c>family.EventType</c> plus the salient FINANCIAL facts the engine decided for that flow, in
/// integer cents. The fields are an ordered, name→cents map so the sealed corpus is auditor-readable
/// (BdP supervision / DORA due-diligence) and a single drifted cent fails the gate.
/// </summary>
/// <remarks>
/// Only the financial / structural-integer fields are sealed — NOT the event id, valid time, or any
/// PII (there is none on these events, ADR-PC-004 §P2). The values are GENERATED by replaying the
/// engine substrate over <c>canonical-instances.yaml</c> (never hand-authored / hand-fudged): for the
/// periodic / advance / multi-coupon variants the engine withholds 28% (2800 bp) FLOW-BY-FLOW on each
/// coupon's gross and rounds once per cash-flow boundary, so each coupon's net is captured individually
/// and the sealed sum is the genuine flow-by-flow total — never <c>round(gross_total × 0.72)</c>
/// (financial_concepts §5.4).
/// </remarks>
internal sealed record CapturedEvent(string EventType, IReadOnlyList<(string Key, long Cents)> Fields)
{
    /// <summary>Equality that the depth-5 gate uses: the event type and the exact ordered cents fields.</summary>
    public bool Matches(CapturedEvent other) =>
        EventType == other.EventType
        && Fields.Count == other.Fields.Count
        && Fields.Zip(other.Fields).All(p => p.First.Key == p.Second.Key && p.First.Cents == p.Second.Cents);

    public string Describe() =>
        $"{EventType} {{ {string.Join(", ", Fields.Select(f => $"{f.Key}={f.Cents}"))} }}";
}

/// <summary>
/// The sealed expected-events corpus (ADR-PC-007 §P5): per <c>test_id</c>, the ordered sequence of
/// <see cref="CapturedEvent"/> the engine + pinned pack are expected to emit for that canonical
/// instance. Persisted as <c>packs/pt.2026.1/test-corpus/expected-events.yaml</c> and compared
/// field-for-field by the depth-5 gate, so the corpus cannot silently drift.
/// </summary>
internal static class ExpectedEventsCorpus
{
    /// <summary>Extract the sealed financial facts of one decided event, in a deterministic field order.
    /// Money is captured cents-native (the engine's source-of-truth representation, ADR-PC-010 §P1); the
    /// figures are whatever the engine DECIDED (flow-by-flow withholding), never recomputed here.</summary>
    public static CapturedEvent Capture(DomainEvent @event)
    {
        // The capture is exhaustive over the lifecycle events the depth-5 corpus drives. A new event on a
        // corpus path that is not handled here fails loud rather than silently sealing nothing.
        return @event switch
        {
            DepositConstituted e => new CapturedEvent("term_deposit.DepositConstituted",
            [
                ("principal_cents", e.Principal.Cents),
                ("tan_basis_points", e.TanBasisPoints),
                ("term_days", e.TermDays),
            ]),
            InterestAccrued e => new CapturedEvent("term_deposit.InterestAccrued",
            [
                ("gross_interest_cents", e.GrossInterest.Cents),
            ]),
            WithholdingApplied e => new CapturedEvent("term_deposit.WithholdingApplied",
            [
                ("tax_cents", e.Tax.Cents),
                ("net_cents", e.Net.Cents),
            ]),
            InterestPaid e => new CapturedEvent("term_deposit.InterestPaid",
            [
                ("gross_interest_cents", e.GrossInterest.Cents),
                ("withholding_tax_cents", e.WithholdingTax.Cents),
                ("net_interest_cents", e.NetInterest.Cents),
            ]),
            DepositMatured e => new CapturedEvent("term_deposit.DepositMatured",
            [
                ("principal_returned_cents", e.PrincipalReturned.Cents),
                ("net_interest_paid_cents", e.NetInterestPaid.Cents),
                ("total_payout_cents", e.TotalPayout.Cents),
            ]),
            DepositTerminatedEarly e => new CapturedEvent("term_deposit.DepositTerminatedEarly",
            [
                ("principal_returned_cents", e.PrincipalReturned.Cents),
                ("penalty_amount_cents", e.PenaltyAmount.Cents),
                ("net_settlement_amount_cents", e.NetSettlementAmount.Cents),
            ]),
            DepositPartiallyWithdrawn e => new CapturedEvent("term_deposit.DepositPartiallyWithdrawn",
            [
                ("withdrawn_amount_cents", e.WithdrawnAmount.Cents),
                ("remaining_principal_cents", e.RemainingPrincipal.Cents),
            ]),
            _ => throw new InvalidOperationException(
                $"depth-5 corpus capture has no rule for event type {@event.GetType().Name}; add it to " +
                "ExpectedEventsCorpus.Capture so the sealed corpus stays exhaustive."),
        };
    }

    /// <summary>The committed sealed corpus path under the pinned pack's test-corpus directory.</summary>
    public static string Path(string repoRoot) =>
        System.IO.Path.Combine(repoRoot, "packs", "pt.2026.1", "test-corpus", "expected-events.yaml");

    /// <summary>True when the committed file is the legacy empty placeholder (<c>expected: []</c>) rather
    /// than a generated corpus — the depth-5 gate fails loud in that case (F.8: no logged skip).</summary>
    public static bool IsPlaceholder(string yaml) =>
        !yaml.Contains("test_id:", StringComparison.Ordinal);

    /// <summary>
    /// Parse the sealed corpus into <c>test_id → ordered CapturedEvent list</c>. The hand-rolled scanner
    /// reads the committed shape (a flat <c>tests:</c> list, each with an <c>events:</c> sub-list of
    /// <c>{ type, fields }</c>) — the test tier carries no YAML library, mirroring CanonicalCorpus.
    /// </summary>
    public static IReadOnlyDictionary<string, IReadOnlyList<CapturedEvent>> Parse(string yaml)
    {
        var result = new Dictionary<string, IReadOnlyList<CapturedEvent>>(StringComparer.Ordinal);
        string? currentTestId = null;
        List<CapturedEvent>? currentEvents = null;
        string? currentType = null;
        List<(string, long)>? currentFields = null;

        void FlushEvent()
        {
            if (currentType is not null && currentFields is not null)
            {
                currentEvents!.Add(new CapturedEvent(currentType, currentFields));
            }

            currentType = null;
            currentFields = null;
        }

        void FlushTest()
        {
            FlushEvent();
            if (currentTestId is not null && currentEvents is not null)
            {
                result[currentTestId] = currentEvents;
            }

            currentTestId = null;
            currentEvents = null;
        }

        foreach (var raw in yaml.Split('\n'))
        {
            var line = StripComment(raw);
            if (line.Trim().Length == 0)
            {
                continue;
            }

            var trimmed = line.TrimStart();

            if (trimmed.StartsWith("- test_id:", StringComparison.Ordinal))
            {
                FlushTest();
                currentTestId = Value(trimmed["- test_id:".Length..]);
                currentEvents = [];
                continue;
            }

            if (trimmed.StartsWith("- type:", StringComparison.Ordinal))
            {
                FlushEvent();
                currentType = Value(trimmed["- type:".Length..]);
                currentFields = [];
                continue;
            }

            // A field line under the current event's `fields:` map, e.g. "    gross_interest_cents: 21900".
            if (currentFields is not null && trimmed.Contains(':', StringComparison.Ordinal)
                && !trimmed.StartsWith("events:", StringComparison.Ordinal)
                && !trimmed.StartsWith("fields:", StringComparison.Ordinal))
            {
                var colon = trimmed.IndexOf(':');
                var key = trimmed[..colon].Trim();
                var value = trimmed[(colon + 1)..].Trim();
                if (long.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var cents))
                {
                    currentFields.Add((key, cents));
                }
            }
        }

        FlushTest();
        return result;
    }

    /// <summary>Render the generated corpus to the committed YAML shape — the GENERATED artefact the
    /// depth-5 gate seals (written only by the explicit regeneration run, never hand-authored).</summary>
    public static string Render(IReadOnlyList<(string TestId, string VariantId, IReadOnlyList<CapturedEvent> Events)> entries)
    {
        var sb = new StringBuilder();
        sb.Append(
            "# GENERATED ARTEFACT — DO NOT HAND-AUTHOR (ADR-PC-007 §P5).\n" +
            "#\n" +
            "# expected-events.yaml is produced by replaying the engine's hand-rolled substrate over\n" +
            "# canonical-instances.yaml and committing the result, so the sealed corpus cannot silently\n" +
            "# drift. The depth-5 simulation gate (C.3, PackSimulationDepth5Tests) asserts the replayed\n" +
            "# event sequences field-for-field against this file and FAILS CI on any drift (F.8, bd up7t).\n" +
            "#\n" +
            "# Regenerate with: BABELSTONE_DEPTH5_GENERATE=1 dotnet test on PackSimulationDepth5Tests.\n" +
            "#\n" +
            "# Every cents figure is what the ENGINE DECIDED, never hand-fudged. For the periodic / advance\n" +
            "# / multi-coupon variants withholding is FLOW-BY-FLOW: 28% (2800 bp) on EACH coupon's gross,\n" +
            "# rounded ONCE per cash-flow boundary, then summed — never round(gross_total × 0.72) and never\n" +
            "# TANL = TANB × 0.72 (financial_concepts §5.4).\n" +
            "tests:\n");

        foreach (var (testId, variantId, events) in entries)
        {
            sb.Append($"  - test_id: {testId}\n");
            sb.Append($"    variant_id: {variantId}\n");
            sb.Append("    events:\n");
            foreach (var e in events)
            {
                sb.Append($"      - type: {e.EventType}\n");
                sb.Append("        fields:\n");
                foreach (var (key, cents) in e.Fields)
                {
                    sb.Append($"          {key}: {cents.ToString(CultureInfo.InvariantCulture)}\n");
                }
            }
        }

        return sb.ToString();
    }

    private static string Value(string afterColon) => afterColon.Trim();

    private static string StripComment(string line)
    {
        var hash = line.IndexOf('#');
        return hash < 0 ? line : line[..hash];
    }
}
