<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Babelstone.Families.CreditoPessoal.Application/Babelstone.Families.CreditoPessoal.Application.csproj" />
    <ProjectReference Include="../../src/Babelstone.Families.CreditoPessoal/Babelstone.Families.CreditoPessoal.csproj" />
    <ProjectReference Include="../../../../engine/src/Babelstone.FinancialMath/Babelstone.FinancialMath.csproj" />
  </ItemGroup>
</Project>
