// <auto-generated>
//     Generated by scripts/gen-saga-topics.py from the AsyncAPI catalogue
//     (contracts/catalog/events/*.asyncapi.yaml). DO NOT EDIT BY HAND.
//
//     The family-integration Kafka topics the saga subscribes to, DERIVED from the catalogue
//     channels (topic == channel == aggregate_type — the relay's documented convention,
//     OutboxDrainer.PublishAsync). Regenerate with `make gen-saga-topics`; the CI gate
//     `make gen-saga-topics-check` fails the build (never a runtime stall, ADR-IC-003) if this
//     drifts from the catalogue. Keeping the runtime on a generated CONSTANT — not a YAML read —
//     preserves the orchestrator/family's depends-only-on-Confluent.Kafka boundary (ADR-IC-003
//     §A8); an explicit list (not a Kafka SubscribePattern regex) keeps one-group-per-consumer
//     intact (ADR-IC-001).
// </auto-generated>

namespace Babelstone.Families.TermDeposit.Orchestration;

/// <summary>
/// The catalogue-derived family-integration topics for the <c>term-deposit</c> family (generated —
/// see the header). Exhaustive and correct AT STARTUP by construction: it is exactly the set of
/// AsyncAPI catalogue channels the family owns, CI-gated against the catalogue.
/// </summary>
public static class FamilyIntegrationTopics
{
    /// <summary>The family-integration Kafka topics, derived from the catalogue channels.</summary>
    public static readonly IReadOnlyList<string> All =
    [
        "term_deposit",
    ];
}
