#!/usr/bin/env python3
"""Generate the docs/product-management/reference/ tree (ADR-PC-022 §P2).

The generated reference quadrant (ADR-PC-022) is **generated, never
hand-edited** — rendered from the machine-readable contracts so it cannot drift
from them. Five renderers, one per source kind:

  events/         <- contracts/avro/**/*.avsc        (Avro record schemas)
  family-schemas/ <- contracts/cue/**/*.cue          (CUE family contracts, via `cue def`)
  mcp-tools/      <- mcp-server/.../server.py         (@mcp.tool()-decorated functions, via AST)
  adr-index/      <- docs/**/adrs/ADR-*.md            (ADR front-matter, cross-namespace)
  pack-format/    <- contracts/cue/pack/pack.cue      (the pack manifest schema, via `cue def`)

Output is **deterministic**: sources are visited in sorted order, no timestamps
or absolute paths are emitted, and `cue def` runs against the mise-pinned CUE —
so `--check` (used by `make docs-verify`) diffs cleanly in CI.

Usage:
    generate.py            # write the reference tree
    generate.py --check    # regenerate in memory, diff against disk, exit 1 on drift
"""
from __future__ import annotations

import ast
import json
import re
import subprocess
import sys
from pathlib import Path

# repo root = three levels up from this file (scripts/docs-gen/generate.py)
ROOT = Path(__file__).resolve().parents[2]
REF = ROOT / "docs" / "product-management" / "reference"
ADR_DIRS = [
    ROOT / "docs" / "product-management" / "product_concepts" / "adrs",
    ROOT / "docs" / "product-management" / "integration_concepts" / "adrs",
]

ADR_RE = re.compile(r"ADR-(?:PC|IC)-\d{3}")


def banner(source_rel: str) -> str:
    return (
        f"<!-- DO NOT EDIT — generated by scripts/docs-gen/generate.py "
        f"from {source_rel}. Run: make docs-gen -->\n"
    )


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def adr_slug_map() -> dict[str, str]:
    """Map ADR id (ADR-PC-022) -> its path within the adrs/ dir (ADR-PC-022-...md, or
    retired/ADR-PC-014-...md for Superseded/Withdrawn ADRs), for linkifying."""
    out: dict[str, str] = {}
    for d in ADR_DIRS:
        for f in sorted(d.glob("ADR-*.md")):
            m = ADR_RE.match(f.name)
            if m:
                out[m.group(0)] = f.name
        for f in sorted((d / "retired").glob("ADR-*.md")):  # ADR-PC-000 §D5: retired ADRs live here
            m = ADR_RE.match(f.name)
            if m:
                out[m.group(0)] = f"retired/{f.name}"
    return out


def adr_link(adr_id: str, slug: str, prefix: str = "../../") -> str:
    """Relative link to an ADR file. `prefix` is the path from the page's own
    directory up to docs/product-management/ (../../ for a reference/<set>/ page,
    ../ for reference/glossary.md which sits one level shallower)."""
    ns = "product_concepts" if "-PC-" in adr_id else "integration_concepts"
    return f"{prefix}{ns}/adrs/{slug}"


def linkify_adrs(text: str, slugs: dict[str, str], prefix: str = "../../") -> str:
    """Turn bare ADR ids in prose into links (the id only; any §-anchor stays text)."""
    def repl(m: re.Match) -> str:
        aid = m.group(0)
        if aid in slugs:
            return f"[{aid}]({adr_link(aid, slugs[aid], prefix)})"
        return aid
    return ADR_RE.sub(repl, text)


def adr_refs(text: str, slugs: dict[str, str], prefix: str = "../../") -> list[str]:
    """Sorted unique ADR ids mentioned in text, as markdown links."""
    found = sorted({m for m in ADR_RE.findall(text) if m in slugs})
    return [f"[{aid}]({adr_link(aid, slugs[aid], prefix)})" for aid in found]


def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


# --------------------------------------------------------------------------
# Renderer 1 — events (Avro .avsc)
# --------------------------------------------------------------------------
def avro_type(t) -> str:
    """Render an Avro type (string | dict | list union) into a compact display string."""
    if isinstance(t, str):
        return f"`{t}`"
    if isinstance(t, list):
        return " \\| ".join(avro_type(x) for x in t)
    if isinstance(t, dict):
        base = t.get("type", "?")
        logical = t.get("logicalType")
        if logical:
            return f"`{base}` (`{logical}`)"
        if base == "array":
            return f"`array<`{avro_type(t.get('items'))}`>`".replace("``", "`")
        return f"`{base}`"
    return "`?`"


def render_events(slugs: dict[str, str]) -> dict[str, str]:
    pages: dict[str, str] = {}
    src_dir = ROOT / "contracts" / "avro"
    files = sorted(src_dir.rglob("*.avsc"))
    index_rows = []
    for f in files:
        schema = json.loads(f.read_text())
        ns = schema.get("namespace", "")
        name = schema.get("name", f.stem)
        full = f"{ns}.{name}" if ns else name
        doc = schema.get("doc", "")
        out = [banner(rel(f)), f"# `{full}`\n"]
        if doc:
            out.append(linkify_adrs(doc, slugs) + "\n")
        out.append("## Payload fields\n")
        out.append("| Field | Type | Description |")
        out.append("|---|---|---|")
        for fld in schema.get("fields", []):
            fdoc = linkify_adrs(fld.get("doc", ""), slugs).replace("|", "\\|")
            out.append(f"| `{fld['name']}` | {avro_type(fld['type'])} | {fdoc} |")
        refs = adr_refs(doc + " " + " ".join(fl.get("doc", "") for fl in schema.get("fields", [])), slugs)
        if refs:
            out.append("\n## Governing ADRs\n")
            out.append(", ".join(refs) + "\n")
        pages[f"events/{full}.md"] = "\n".join(out).rstrip() + "\n"
        index_rows.append(f"| [`{full}`](./{full}.md) | {linkify_adrs(doc, slugs).splitlines()[0] if doc else ''} |")

    idx = [
        banner("contracts/avro/**/*.avsc"),
        "# Events\n",
        "Avro record schemas the engine emits — the business payload only "
        "(the CloudEvents envelope rides in Kafka headers). Generated from "
        "`contracts/avro/`.\n",
        "| Event | Summary |",
        "|---|---|",
        *index_rows,
    ]
    pages["events/README.md"] = "\n".join(idx).rstrip() + "\n"
    return pages


# --------------------------------------------------------------------------
# Renderer 2 — family schemas (CUE, via `cue def`)
# --------------------------------------------------------------------------
def cue_def(args: list[str], cwd: Path) -> str:
    """Run `cue def` under the mise-pinned toolchain; return canonical schema text."""
    proc = subprocess.run(
        ["mise", "exec", "--", "cue", "def", *args],
        cwd=cwd, capture_output=True, text=True,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"cue def {args} failed:\n{proc.stderr}")
    return proc.stdout.rstrip()


def render_family_schemas(slugs: dict[str, str]) -> dict[str, str]:
    pages: dict[str, str] = {}
    cue_dir = ROOT / "contracts" / "cue"
    families = sorted((cue_dir / "families").glob("*.cue"))
    index_rows = []
    for f in families:
        # canonical, fully-resolved schema for this family + the shared vocabulary
        canonical = cue_def([f"families/{f.name}", "common.cue", "-p", "family"], cwd=cue_dir)
        stem = f.stem
        out = [
            banner(rel(f)),
            f"# Family schema — `{stem}`\n",
            f"The closed CUE contract a `{stem}` variant YAML must satisfy "
            "(no DSL escape hatch — a field the schema does not declare is "
            "rejected). Canonical, fully-resolved form via `cue def`; the "
            "authored source is `" + rel(f) + "`.\n",
            "```cue",
            canonical,
            "```",
        ]
        refs = adr_refs(f.read_text(), slugs)
        if refs:
            out += ["\n## Governing ADRs\n", ", ".join(refs) + "\n"]
        pages[f"family-schemas/{stem}.md"] = "\n".join(out).rstrip() + "\n"
        index_rows.append(f"| [`{stem}`](./{stem}.md) |")

    idx = [
        banner("contracts/cue/families/*.cue"),
        "# Family schemas\n",
        "The CUE constraint contracts a product-family variant must satisfy "
        "(ADR-PC-006). Generated from `contracts/cue/families/`.\n",
        "| Family |",
        "|---|",
        *index_rows,
    ]
    pages["family-schemas/README.md"] = "\n".join(idx).rstrip() + "\n"
    return pages


# --------------------------------------------------------------------------
# Renderer 3 — MCP tools (server.py, via AST)
# --------------------------------------------------------------------------
def is_tool_decorator(dec: ast.expr) -> bool:
    # matches @mcp.tool() and @mcp.tool
    node = dec.func if isinstance(dec, ast.Call) else dec
    return isinstance(node, ast.Attribute) and node.attr == "tool"


def render_mcp_tools(slugs: dict[str, str]) -> dict[str, str]:
    pages: dict[str, str] = {}
    src = ROOT / "mcp-server" / "src" / "babelstone_mcp" / "server.py"
    tree = ast.parse(src.read_text())
    index_rows = []
    tools = []
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and any(
            is_tool_decorator(d) for d in node.decorator_list
        ):
            tools.append(node)
    for node in sorted(tools, key=lambda n: n.name):
        name = node.name
        doc = ast.get_docstring(node) or ""
        out = [banner(rel(src)), f"# `{name}`\n"]
        if doc:
            out.append(linkify_adrs(doc.strip(), slugs) + "\n")
        out.append("## Signature\n")
        out.append("| Parameter | Type | Default |")
        out.append("|---|---|---|")
        args = node.args
        defaults = [None] * (len(args.args) - len(args.defaults)) + list(args.defaults)
        for a, d in zip(args.args, defaults):
            if a.arg == "self":
                continue
            ann = f"`{ast.unparse(a.annotation)}`" if a.annotation else ""
            dv = f"`{ast.unparse(d)}`" if d is not None else "—"
            out.append(f"| `{a.arg}` | {ann} | {dv} |")
        ret = f"`{ast.unparse(node.returns)}`" if node.returns else "—"
        out.append(f"\n**Returns:** {ret}\n")
        pages[f"mcp-tools/{name}.md"] = "\n".join(out).rstrip() + "\n"
        summary = linkify_adrs(doc.strip().splitlines()[0], slugs) if doc.strip() else ""
        index_rows.append(f"| [`{name}`](./{name}.md) | {summary} |")

    idx = [
        banner("mcp-server/src/babelstone_mcp/server.py"),
        "# MCP tools\n",
        "The bank-as-MCP-server tool surface (ADR-IC-010) an LLM agent calls. "
        "Generated from the `@mcp.tool()`-decorated functions in "
        "`mcp-server/src/babelstone_mcp/server.py`.\n",
        "| Tool | Summary |",
        "|---|---|",
        *index_rows,
    ]
    pages["mcp-tools/README.md"] = "\n".join(idx).rstrip() + "\n"
    return pages


# --------------------------------------------------------------------------
# Renderer 4 — ADR cross-namespace index
# --------------------------------------------------------------------------
def parse_adr(path: Path) -> dict[str, str]:
    text = path.read_text()
    title = ""
    lines = text.splitlines()
    for line in lines:
        if line.startswith("# "):
            title = line[2:].strip()
            break
    # Parse ONLY the first contiguous table (the front-matter | Field | Value |
    # block), not every two-cell row in the document — and keep the first value
    # seen for each field.
    fields: dict[str, str] = {}
    in_table = False
    for line in lines:
        stripped = line.strip()
        is_row = stripped.startswith("|") and stripped.endswith("|")
        if is_row:
            in_table = True
            cells = [c.strip() for c in stripped.strip("|").split("|")]
            if len(cells) != 2 or set(cells[0]) <= {"-", ":"}:
                continue  # separator row or not a 2-col field/value row
            key = cells[0].lower()
            if key not in fields:
                fields[key] = cells[1]
        elif in_table:
            break  # first table ended
    return {
        "title": title,
        "status": fields.get("status", ""),
        "shape": fields.get("shape", ""),
        "date": fields.get("date", ""),
    }


def strip_md(text: str) -> str:
    # flatten any markdown link in a status cell to its text, drop stray pipes
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    return text.replace("|", "\\|")


def render_adr_index(slugs: dict[str, str]) -> dict[str, str]:
    pages: dict[str, str] = {}
    sections = []
    for d, ns_label, ns_dir in [
        (ADR_DIRS[0], "ADR-PC — Product engine", "product_concepts"),
        (ADR_DIRS[1], "ADR-IC — Integration estate", "integration_concepts"),
    ]:
        rows = ["", f"## {ns_label}\n", "| # | Title | Shape | Status |", "|---|---|---|---|"]
        adr_files = [(f, f.name) for f in d.glob("ADR-*.md")]
        adr_files += [(f, f"retired/{f.name}") for f in (d / "retired").glob("ADR-*.md")]
        for f, relpath in sorted(adr_files, key=lambda x: x[0].name):
            m = ADR_RE.match(f.name)
            if not m:
                continue
            info = parse_adr(f)
            num = m.group(0).split("-")[-1]
            # title without the "ADR-XX-NNN: " prefix
            t = re.sub(r"^ADR-(?:PC|IC)-\d{3}:\s*", "", info["title"])
            link = f"../../{ns_dir}/adrs/{relpath}"
            rows.append(
                f"| [{num}]({link}) | {strip_md(t)} | {strip_md(info['shape']) or '—'} "
                f"| {strip_md(info['status']) or '—'} |"
            )
        sections.append("\n".join(rows))

    out = [
        banner("docs/product-management/**/adrs/ADR-*.md"),
        "# ADR index (cross-namespace)\n",
        "Every Architectural Decision Record across **both** namespaces, in one "
        "place — the joint landscape the per-namespace indexes do not give. "
        "Generated from each ADR's front-matter; the per-namespace README "
        "indexes ([ADR-PC](../../product_concepts/adrs/README.md) · "
        "[ADR-IC](../../integration_concepts/adrs/README.md)) carry the full "
        "decision summaries.\n",
        *sections,
    ]
    pages["adr-index/README.md"] = "\n".join(out).rstrip() + "\n"
    return pages


# --------------------------------------------------------------------------
# Renderer 5 — pack format
# --------------------------------------------------------------------------
def render_pack_format(slugs: dict[str, str]) -> dict[str, str]:
    pages: dict[str, str] = {}
    cue_dir = ROOT / "contracts" / "cue"
    pack_cue = cue_dir / "pack" / "pack.cue"
    canonical = cue_def(["pack/pack.cue", "-p", "pack"], cwd=cue_dir)
    out = [
        banner(rel(pack_cue)),
        "# Pack manifest format\n",
        "The CUE schema a signed regulatory pack's manifest must satisfy "
        "(ADR-PC-007). A pack bundles a digest-pinned copy of the family "
        "schemas plus this manifest; it is distributed as a cosign-signed OCI "
        "artefact, pulled by digest. Canonical form via `cue def`; authored "
        "source is `" + rel(pack_cue) + "`.\n",
        "```cue",
        canonical,
        "```",
    ]
    refs = adr_refs(pack_cue.read_text(), slugs)
    if refs:
        out += ["\n## Governing ADRs\n", ", ".join(refs) + "\n"]
    pages["pack-format/README.md"] = "\n".join(out).rstrip() + "\n"
    return pages


# --------------------------------------------------------------------------
# Renderer 6 — glossary (hand-authored term source -> sorted, linkified page)
# --------------------------------------------------------------------------
def render_glossary(slugs: dict[str, str]) -> dict[str, str]:
    src = ROOT / "scripts" / "docs-gen" / "glossary-source.md"
    rows: list[tuple[str, str]] = []
    for line in src.read_text().splitlines():
        s = line.strip()
        if not (s.startswith("|") and s.endswith("|")):
            continue
        cells = [c.strip() for c in s.strip("|").split("|")]
        if len(cells) != 2 or set(cells[0]) <= {"-", ":"} or cells[0].lower() == "term":
            continue
        rows.append((cells[0], cells[1]))
    rows.sort(key=lambda r: r[0].lower())
    out = [
        banner(rel(src)),
        "# Glossary\n",
        "Canonical one-line definitions for the vocabulary used across the "
        "corpus. Each term is defined **once, here** — the generated reference is "
        "the single home for the vocabulary; other corpus docs link to this page "
        "(e.g. `glossary.md#family`) rather than redefining terms ([ADR-PC-022 §P1]"
        "(../product_concepts/adrs/ADR-PC-022-product-documentation-architecture.md)). "
        "For the full treatment, follow the linked ADR or concept doc.\n",
        "| Term | Definition |",
        "|---|---|",
    ]
    # glossary.md lives in reference/ (one level shallower than reference/<set>/)
    for term, dfn in rows:
        out.append(
            f'| <a id="{slugify(term)}"></a>**{term}** '
            f"| {linkify_adrs(dfn, slugs, prefix='../')} |"
        )
    return {"glossary.md": "\n".join(out).rstrip() + "\n"}


# --------------------------------------------------------------------------
# Top-level index + driver
# --------------------------------------------------------------------------
def render_root_index() -> dict[str, str]:
    out = [
        banner("scripts/docs-gen/generate.py"),
        "# Reference\n",
        "**Generated, exhaustive, dry** — the generated lookup quadrant "
        "([ADR-PC-022 §P2]"
        "(../product_concepts/adrs/ADR-PC-022-product-documentation-architecture.md)). "
        "Every page here is rendered from a machine-readable source and "
        "regenerated-and-diffed in CI, so it **cannot drift**. Do not hand-edit; "
        "run `make docs-gen`.\n",
        "| Set | Source | What |",
        "|---|---|---|",
        "| [events/](./events/README.md) | `contracts/avro/` | Avro payload schemas the engine emits |",
        "| [family-schemas/](./family-schemas/README.md) | `contracts/cue/families/` | CUE family contracts a variant must satisfy |",
        "| [mcp-tools/](./mcp-tools/README.md) | `mcp-server/` | the bank-as-MCP-server tool surface |",
        "| [adr-index/](./adr-index/README.md) | `docs/**/adrs/` | every ADR, both namespaces, one table |",
        "| [pack-format/](./pack-format/README.md) | `contracts/cue/pack/` | the signed-pack manifest schema |",
        "| [glossary.md](./glossary.md) | `scripts/docs-gen/glossary-source.md` | the single home for the corpus vocabulary |",
    ]
    return {"README.md": "\n".join(out).rstrip() + "\n"}


def build() -> dict[str, str]:
    slugs = adr_slug_map()
    pages: dict[str, str] = {}
    pages.update(render_root_index())
    pages.update(render_events(slugs))
    pages.update(render_family_schemas(slugs))
    pages.update(render_mcp_tools(slugs))
    pages.update(render_adr_index(slugs))
    pages.update(render_pack_format(slugs))
    pages.update(render_glossary(slugs))
    return pages


def main() -> int:
    check = "--check" in sys.argv[1:]
    pages = build()
    generated = {(REF / p) for p in pages}

    if check:
        drift = []
        for p, content in sorted(pages.items()):
            disk = REF / p
            if not disk.exists():
                drift.append(f"missing:  reference/{p}")
            elif disk.read_text() != content:
                drift.append(f"changed:  reference/{p}")
        # stale files present on disk but no longer generated
        for f in sorted(REF.rglob("*.md")):
            if f not in generated:
                drift.append(f"stale:    {f.relative_to(REF.parent).as_posix()}")
        if drift:
            print("docs-verify: reference/ is out of date — run `make docs-gen`:")
            print("\n".join("  " + d for d in drift))
            return 1
        print(f"docs-verify: reference/ is up to date ({len(pages)} pages).")
        return 0

    # write mode
    for p, content in sorted(pages.items()):
        disk = REF / p
        disk.parent.mkdir(parents=True, exist_ok=True)
        disk.write_text(content)
    # prune stale generated pages
    for f in sorted(REF.rglob("*.md")):
        if f not in generated:
            f.unlink()
    print(f"docs-gen: wrote {len(pages)} reference pages to {rel(REF)}/.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
